version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: db-monetenmanager
    restart: always
    environment:
      POSTGRES_DB: monetenmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "6789:5432"
    volumes:
      - monetenmanager-data:/var/lib/postgresql/data

volumes:
  monetenmanager-data:
